//NAVIGATION
export const NAVIGATE = 'NAVIGATE';

//ACCOUNT
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FAIL_LOGIN = 'FAIL_LOGIN';
export const FAIL_CREATE_USER = 'FAIL_CREATE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CREATE_USER = 'CREATE_USER';
export const GET_USER_AUTH = 'GET_USER_AUTH';

//POST
export const OPEN_POST_FORM = 'OPEN_POST_FORM';
export const CLOSE_POST_FORM = 'CLOSE_POST_FORM';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const STORE_USER_DETAILS = 'SUBMIT_USER_DETAILS';
export const STORE_MISSION_DETAILS = 'SUBMIT_MISSION_DETAILS';
export const STORE_PARTY_DETAILS = 'SUBMIT_PARTY_DETAILS';
export const GENERATE_QUESTIONS = 'GENERATE_QUESTIONS';
export const CONTINUE_POST_WIZARD = 'CONTINUE_POST_WIZARD';
export const POST_FORM = 'POST_FORM';

//FILTERS
export const TOGGLE_ADVANCED_FILTER = 'TOGGLE_ADVANCED_FILTER';
export const CHANGE_FILTER = 'CHANGE_FILTER';

//ACCOUNT DIALOG
export const SHOW_ACCOUNT_DIALOG = 'SHOW_ACCOUNT_DIALOG';
export const HIDE_ACCOUNT_DIALOG = 'HIDE_ACCOUNT_DIALOG';
